version: "3.8"

volumes:
   mariadb_vol:

networks:
  mariadb_net:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    # ports:
    #   - 3306:3306
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}      
    networks:
      - mariadb_net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PWD}
    networks:
      - mariadb_net