version: "3.8"

services:
  redisdb:
    image: redis:7.0-alpine
    container_name: redisdb
    restart: always
    # ports:
    #   - 6379:6379
    volumes:
      - redisdata_vol:/data
    networks:
      - redisdb_net

  rediscommander:
    image: rediscommander/redis-commander:latest
    container_name: rediscommander
    restart: always
    depends_on:
      - redisdb
    ports:
      - 8080:8081
    environment:
      REDIS_HOSTS: local:redisdb:6379
    networks:
      - redisdb_net

volumes:
   redisdata_vol:

networks:
  redisdb_net:
    driver: bridge