version: "3.8"

volumes:
   app-vol:
   db-vol:

networks:
  wp-net:
    driver: bridge

services:

  wp-db:
    image: mysql:8.0.30
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PWD}
      MYSQL_DATABASE: ${DB_DB_NAME}
    networks:
      - wp-net

  wp-app:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    depends_on:
      - wp-db
    volumes:
      - app-vol:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: ${DB_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PWD}
      WORDPRESS_DB_NAME: ${DB_DB_NAME}
    networks:
      - wp-net