version: "3.8"

volumes:
   mongo_vol:

networks:
  mongo_net:
    driver: bridge

services:
  mongo-db:
    image: mongo:4.4.3
    container_name: mongo-container
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    networks:
      - mongo_net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo-db
    ports:
      - 8080:8081
    environment:      
      ME_CONFIG_MONGODB_SERVER: mongo-db 
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PWD}
    networks:
      - mongo_net
