version: "3.8"

volumes:
   pgdata_vol:

networks:
  pgdb_net:
    driver: bridge

services:
  pgdb:
    image: postgres:14.5-alpine
    container_name: pgdb
    restart: always
    # ports:
    #   - 5432:5432
    volumes:
      - pgdata_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
    networks:
      - pgdb_net

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    restart: always
    depends_on:
      - pgdb
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER_NAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_USER_PWD}
    networks:
      - pgdb_net
